azure:
  oauth2-base-url: https://login.microsoftonline.com/
  tenant-id: ${AZURE_TENANT_ID}
  oauth2-api-path: oauth2/v2.0/authorize
  client-id: ${AZURE_CLIENT_ID}
  launchpad-redirectUri: https://launchpad-auth-preprod.hmpps.service.justice.gov.uk/v1/oauth2/callback
launchpad:
  iss-url: https://launchpad-auth-preprod.hmpps.service.justice.gov.uk
auth:
  service:
    secret: random_secret_random_secret_random_secret
spring:
  application:
    name: hmpps-launchpad-auth
  codec:
    max-in-memory-size: 10MB
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
  #change password later when dev environment is set up
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/launchpad
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_ENDPOINT}//launchpad
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true