---
# For dev environment with API Gateway access via VPC Link

purge_inactive_users_schedule: "0 13 * * 1-5"

purge_stale_sso_tokens_schedule: "05-55/10 07-21 * * 1-5"

generic-service:
  replicaCount: 2

  ingress:
    host: launchpad-auth-dev.internal-non-prod.cloud-platform.service.justice.gov.uk

    # Use internal ingress controller for API Gateway access via VPC Link
    className: internal-non-prod
    modsecurity_enabled: false
    #annotations:
      # Disable SSL redirect to allow HTTP traffic from API Gateway via VPC Link
      #nginx.ingress.kubernetes.io/ssl-redirect: "false"

  scheduledDowntime:
    enabled: true

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SPRING_PROFILES_ACTIVE: "dev"
    ENVIRONMENT_NAME: "dev"

  allowlist:
    unrestricted: "0.0.0.0/0"
#    groups:
#      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-launchpad-nonprod
  businessHoursOnly: true
