{{- if .Values.apiGatewayIngress.enabled -}}
{{- $fullName := include "generic-service.fullname" . -}}
{{- $svcPort := index .Values "generic-service" "image" "port" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-api-gateway
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
  {{- with .Values.apiGatewayIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiGatewayIngress.className }}
  ingressClassName: {{ .Values.apiGatewayIngress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.apiGatewayIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
