{{- $genericService := index .Values "generic-service" }}
{{- $fullName := include "generic-service.fullname" . }}
{{- $svcPort := index $genericService "image" "port" | default 8080 }}
{{- if $genericService }}
{{- $apiGatewayIngress := index $genericService "apiGatewayIngress" }}
{{- if and $apiGatewayIngress (index $apiGatewayIngress "enabled") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-api-gateway
  labels:
    {{- $imageWithTag := dict "tag" "" }}
    {{- if index $genericService "image" }}
    {{- $imageWithTag = merge $imageWithTag (index $genericService "image") }}
    {{- end }}
    {{- $genericValues := merge $genericService (dict "image" $imageWithTag) }}
    {{- $genericCtx := dict "Values" $genericValues "Release" $.Release "Chart" $.Chart "Files" $.Files "Capabilities" $.Capabilities "Template" $.Template }}
    {{- include "generic-service.labels" $genericCtx | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ $fullName }}-api-gateway-{{ $.Release.Namespace }}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  {{- toYaml (index $apiGatewayIngress "annotations") | nindent 4 }}
  {{- end }}
spec:
  {{- if and (index $apiGatewayIngress "className") (ne (index $apiGatewayIngress "className") "") }}
  ingressClassName: {{ index $apiGatewayIngress "className" }}
  {{- end }}
  rules:
    - host: {{ index $apiGatewayIngress "host" | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
{{- end }}
