# For gateway ingress
{{- if index .Values "generic-service" "apiGatewayIngress" "enabled" -}}
{{- $fullName := include "generic-service.fullname" . -}}
{{- $svcPort := index .Values "generic-service" "image" "port" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-api-gateway
  labels:
{{- with index .Values "generic-service" -}}
{{- $genericCtx := dict "Values" . "Release" $.Release "Chart" $.Chart "Files" $.Files "Capabilities" $.Capabilities "Template" $.Template -}}
{{ include "generic-service.labels" $genericCtx | nindent 4 }}
{{- end }}
  {{- with index .Values "generic-service" "apiGatewayIngress" "annotations" }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if index .Values "generic-service" "apiGatewayIngress" "className" }}
  ingressClassName: {{ index .Values "generic-service" "apiGatewayIngress" "className" }}
  {{- end }}
  rules:
    - host: {{ index .Values "generic-service" "apiGatewayIngress" "host" | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
